name: soma_platform
description: SOMA - Plateforme Ã©ducative en RDC
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  url_launcher: ^6.3.0
  video_player: ^2.9.1
  scrollable_positioned_list: ^0.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    # Assets de base requis
    - assets/images/logo_soma.png
    - assets/images/logo_soma_white.png
    - assets/videos/hero_bg.mp4
    - assets/images/team/